import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";
import Sidebar from "./Components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}>
        <div
          className="flex flex-col justify-start bg-red-500  h-screen"
          style={{ height: "calc(10vh - 200px)" }}
        >
          <Header />
          <div
            className="flex flex-1 bg-green-500  "
            style={{ height: "calc(10vh - 200px)" }}
          >
            <main
              className="flex-1 p-6 bg-white overflow-y-auto"
              style={{ height: "calc(100vh - 40px)" }}
            >
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
